export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREASE_QUANTITY = "ADJUST_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";
export const ADD_PRODUCTS = "ADD_PRODUCTS";
export const SET_CURRENT = "SET_CURRENT";
